import React, { useState } from "react";
import Tooltip from "@mui/material/Tooltip";
import TextField from "@mui/material/TextField";

const LocationInputField = ({ value, onChange }) => {
  const [isLocationTooltipActive, setIsLocationTooltipActive] = useState(false);

  return (
    <Tooltip
      title="Location search functionality may not be accurate for local locations as it uses placeholder data generated by the Laravel Faker library."
      open={isLocationTooltipActive}
      arrow
    >
      <TextField
        id="outlined-location"
        label="Location"
        variant="outlined"
        size="small"
        value={value}
        onChange={onChange}
        onFocus={() => setIsLocationTooltipActive(true)}
        onBlur={() => setIsLocationTooltipActive(false)}
      />
    </Tooltip>
  );
};

export default LocationInputField;
